/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author pkm_pondoksalam
 */
public class GUIMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form YEah
     */
    public GUIMainMenu() {
        initComponents();
        ButtonHandler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenu = new javax.swing.JPanel();
        DoNationLabel = new javax.swing.JLabel();
        SloganLogo = new javax.swing.JLabel();
        HomeButton = new javax.swing.JButton();
        AboutUsButton = new javax.swing.JButton();
        BlogButton = new javax.swing.JButton();
        ContactButton = new javax.swing.JButton();
        HowToButton = new javax.swing.JButton();
        SelectYourDonLabel = new javax.swing.JLabel();
        StuffsDonationButton = new javax.swing.JButton();
        BloodDonationButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        RegisterInstButton = new javax.swing.JButton();
        MoneyDonationButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        InstitutionListButton = new javax.swing.JButton();
        AdminButton = new javax.swing.JButton();
        ListMoneyDonation = new javax.swing.JButton();
        ListInKindDonation = new javax.swing.JButton();
        ListBloodDonation = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainMenu.setBackground(new java.awt.Color(0, 102, 102));

        DoNationLabel.setFont(new java.awt.Font("Felix Titling", 1, 36)); // NOI18N
        DoNationLabel.setForeground(new java.awt.Color(255, 255, 255));
        DoNationLabel.setText("DO-NATION");

        SloganLogo.setFont(new java.awt.Font("Bradley Hand ITC", 3, 14)); // NOI18N
        SloganLogo.setForeground(new java.awt.Color(255, 255, 255));
        SloganLogo.setText("Share, Joy, and Love");

        HomeButton.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        HomeButton.setText("Home");
        HomeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        AboutUsButton.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        AboutUsButton.setText("about us");
        AboutUsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BlogButton.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        BlogButton.setText("blog");
        BlogButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ContactButton.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        ContactButton.setText("contact");
        ContactButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        HowToButton.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        HowToButton.setText("how to");
        HowToButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        SelectYourDonLabel.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        SelectYourDonLabel.setForeground(new java.awt.Color(255, 255, 255));
        SelectYourDonLabel.setText("•••   SELECT YOUR DONATION   •••");

        StuffsDonationButton.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        StuffsDonationButton.setText("STUFFS");
        StuffsDonationButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StuffsDonationButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        BloodDonationButton.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        BloodDonationButton.setText("BLOOD");
        BloodDonationButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BloodDonationButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Donate via money,");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fast and reliable.");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Donate via stuffs,");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Fast and reliable.");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Donate via blood,");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Fast and reliable.");

        RegisterInstButton.setText("Register Institution");
        RegisterInstButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        MoneyDonationButton.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        MoneyDonationButton.setText("MONEY");
        MoneyDonationButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MoneyDonationButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        javax.swing.GroupLayout MainMenuLayout = new javax.swing.GroupLayout(MainMenu);
        MainMenu.setLayout(MainMenuLayout);
        MainMenuLayout.setHorizontalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AboutUsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BlogButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContactButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HowToButton)
                .addGap(229, 311, Short.MAX_VALUE))
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(DoNationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                        .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(MainMenuLayout.createSequentialGroup()
                                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MainMenuLayout.createSequentialGroup()
                                        .addGap(178, 178, 178)
                                        .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(MainMenuLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(127, 127, 127))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(MoneyDonationButton)
                                        .addGap(148, 148, 148)))
                                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MainMenuLayout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(150, 150, 150)
                                        .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(MainMenuLayout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(StuffsDonationButton)
                                        .addGap(172, 172, 172)
                                        .addComponent(BloodDonationButton))))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RegisterInstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                        .addComponent(SelectYourDonLabel)
                        .addGap(319, 319, 319))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                        .addComponent(SloganLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(431, 431, 431))))
        );
        MainMenuLayout.setVerticalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainMenuLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(DoNationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(SloganLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HomeButton)
                            .addComponent(AboutUsButton)
                            .addComponent(BlogButton)
                            .addComponent(ContactButton)
                            .addComponent(HowToButton)))
                    .addGroup(MainMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RegisterInstButton)))
                .addGap(76, 76, 76)
                .addComponent(SelectYourDonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StuffsDonationButton)
                    .addComponent(BloodDonationButton)
                    .addComponent(MoneyDonationButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        InstitutionListButton.setText("Institution List");
        InstitutionListButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        AdminButton.setText("Admin");
        AdminButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonActionPerformed(evt);
            }
        });

        ListMoneyDonation.setText("Money D List");
        ListMoneyDonation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListMoneyDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListMoneyDonationActionPerformed(evt);
            }
        });

        ListInKindDonation.setText("InKind D List");
        ListInKindDonation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListInKindDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListInKindDonationActionPerformed(evt);
            }
        });

        ListBloodDonation.setText("Blood D List");
        ListBloodDonation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListBloodDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListBloodDonationActionPerformed(evt);
            }
        });

        LogOutButton.setText("Log Out");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InstitutionListButton, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(AdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListMoneyDonation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListInKindDonation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListBloodDonation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LogOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(MainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(InstitutionListButton)
                .addGap(18, 18, 18)
                .addComponent(AdminButton)
                .addGap(18, 18, 18)
                .addComponent(ListMoneyDonation)
                .addGap(18, 18, 18)
                .addComponent(ListInKindDonation)
                .addGap(18, 18, 18)
                .addComponent(ListBloodDonation)
                .addGap(18, 18, 18)
                .addComponent(LogOutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void AdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonActionPerformed
        new AdminLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AdminButtonActionPerformed

    private void ListMoneyDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListMoneyDonationActionPerformed
        new BloodDonationViewAll().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ListMoneyDonationActionPerformed

    private void ListInKindDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListInKindDonationActionPerformed
        new InKindDonationViewAll().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ListInKindDonationActionPerformed

    private void ListBloodDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListBloodDonationActionPerformed
        new MoneyDonationViewAll().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ListBloodDonationActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        new DonatorPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogOutButtonActionPerformed
    private void MoneyDonationButtonActionPerformed(java.awt.event.ActionEvent evt){
        new MoneyDonationGUI().setVisible(true);
        this.dispose();
    }
    private void StuffsDonationButtonActionPerformed(java.awt.event.ActionEvent evt){
        new InKindDonationGUI().setVisible(true);
        this.dispose();
    }
    private void BloodDonationButtonActionPerformed(java.awt.event.ActionEvent evt){
        new BloodDonationGUI().setVisible(true);
        this.dispose();
    }
    private void InstitutionListButtonActionPerformed(java.awt.event.ActionEvent evt){
        new InstitutionList().setVisible(true);
        this.dispose();
    }
    private void RegisterInstButtonActionPerformed(java.awt.event.ActionEvent evt) {
        new InNeedPage().setVisible(true);
        this.dispose();
    }
    private void AboutUsButtonActionPerformed(java.awt.event.ActionEvent evt){
        showMessage("Easy way to donate stuff","About Us",0);
    }
    private void BlogButtonActionPerformed(java.awt.event.ActionEvent evt){
        showMessage("Do-Nation.blogspot.com","Blog",0);
    }
    private void ContactButtonActionPerformed(java.awt.event.ActionEvent evt){
        showMessage("Line : @Do-Nation","Contact",0);
    }
    private void HowToButtonActionPerformed(java.awt.event.ActionEvent evt){
       showMessage("How-To","Click The Button",0);
    }
    
    private void ButtonHandler(){
         MoneyDonationButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoneyDonationButtonActionPerformed(evt);
            }
        });
           BloodDonationButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodDonationButtonActionPerformed(evt);
            }
        });
             StuffsDonationButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StuffsDonationButtonActionPerformed(evt);
            }
        });
               InstitutionListButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               InstitutionListButtonActionPerformed(evt);
            }
        });
                   RegisterInstButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               RegisterInstButtonActionPerformed(evt);
            }
        });
                   AboutUsButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               AboutUsButtonActionPerformed(evt);
            }
        });
                   ContactButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               ContactButtonActionPerformed(evt);
            }
        });
                   BlogButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               BlogButtonActionPerformed(evt);
            }
        });
                   HowToButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               HowToButtonActionPerformed(evt);
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMainMenu().setVisible(true);
            }
        });
    }
    
        public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUsButton;
    private javax.swing.JButton AdminButton;
    private javax.swing.JButton BlogButton;
    private javax.swing.JButton BloodDonationButton;
    private javax.swing.JButton ContactButton;
    private javax.swing.JLabel DoNationLabel;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton HowToButton;
    private javax.swing.JButton InstitutionListButton;
    private javax.swing.JButton ListBloodDonation;
    private javax.swing.JButton ListInKindDonation;
    private javax.swing.JButton ListMoneyDonation;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JButton MoneyDonationButton;
    private javax.swing.JButton RegisterInstButton;
    private javax.swing.JLabel SelectYourDonLabel;
    private javax.swing.JLabel SloganLogo;
    private javax.swing.JButton StuffsDonationButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
