/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.InNeedInstitution;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author pkm_pondoksalam
 */
public class InNeedPage extends javax.swing.JFrame {

    /**
     * Creates new form D
     */
    public InNeedPage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InNeedPage = new javax.swing.JPanel();
        InNeedTitleLabel = new javax.swing.JLabel();
        InstitutionNameTF = new javax.swing.JTextField();
        RegisterBtn = new javax.swing.JButton();
        RegisterLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InNeedPage.setBackground(new java.awt.Color(0, 102, 102));

        InNeedTitleLabel.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        InNeedTitleLabel.setForeground(new java.awt.Color(240, 240, 240));
        InNeedTitleLabel.setText("In-Need Page");

        InstitutionNameTF.setText("Institution Name");
        InstitutionNameTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        InstitutionNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstitutionNameTFActionPerformed(evt);
            }
        });

        RegisterBtn.setFont(new java.awt.Font("Felix Titling", 0, 13)); // NOI18N
        RegisterBtn.setText("Register");
        RegisterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });

        RegisterLabel.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        RegisterLabel.setForeground(new java.awt.Color(240, 240, 240));
        RegisterLabel.setText("Register");

        javax.swing.GroupLayout InNeedPageLayout = new javax.swing.GroupLayout(InNeedPage);
        InNeedPage.setLayout(InNeedPageLayout);
        InNeedPageLayout.setHorizontalGroup(
            InNeedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InNeedPageLayout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(InNeedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InstitutionNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InNeedPageLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(RegisterBtn)))
                .addGap(146, 146, 146))
            .addGroup(InNeedPageLayout.createSequentialGroup()
                .addGroup(InNeedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InNeedPageLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(RegisterLabel))
                    .addGroup(InNeedPageLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InNeedPageLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(InNeedTitleLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InNeedPageLayout.setVerticalGroup(
            InNeedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InNeedPageLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(InNeedTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RegisterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InstitutionNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(RegisterBtn)
                .addGap(203, 203, 203))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InNeedPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InNeedPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InstitutionNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstitutionNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstitutionNameTFActionPerformed

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        try {  
            Class.forName("com.mysql.jdbc.Driver");  
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/do-nation","root","");  
            InNeedInstitution inst = new InNeedInstitution(302, getInstitutionNameTF());
            
            if ("".equals(getInstitutionNameTF()))
            {
                showMessage("Data can not be Empty!","Error", 0); 
            }else{
                PreparedStatement pst = conn.prepareStatement("INSERT INTO InNeedInstitution VALUES("+ inst.getInNeedPK() + ",'"+ inst.getInstName() +"');");
            
                int rs = pst.executeUpdate();
                if (rs > 0){
                    showMessage("Data Inserted","Pepe", 0);       
                }else{
                    showMessage("Data Fail to Insert","Pepe", 0);       
                }
            }
            conn.close();
            new GUIMainMenu().setVisible(true);
            this.dispose();
        } catch (Exception e) {  
            showMessage("Failed to Connect to Database InNeedInstitution","Error Connection", 0);        
            new GUIMainMenu().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_RegisterBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InNeedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InNeedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InNeedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InNeedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InNeedPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InNeedPage;
    private javax.swing.JLabel InNeedTitleLabel;
    private javax.swing.JTextField InstitutionNameTF;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JLabel RegisterLabel;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the InstitutionNameTF
     */
    public String getInstitutionNameTF() {
        return InstitutionNameTF.getText();
    }

    public void setInstitutionNameTF(String s) {
        this.InstitutionNameTF.setText(s);
    }

    public JButton getRegisterBtn() {
        return RegisterBtn;
    }
    
    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }
    
    public void addActionListener(ActionListener x){
        RegisterBtn.addActionListener(x);
    }
    
}
