/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.InNeedInstitution;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pkm_pondoksalam
 */
public class InstitutionList extends javax.swing.JFrame {

    /**
     * Creates new form InstitutionList
     */
    public InstitutionList() {
        initComponents();
        showInstList();
        ButtonHandler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InstitutionList = new javax.swing.JPanel();
        InstitutionSelectLabel = new javax.swing.JLabel();
        TableInstitution = new javax.swing.JScrollPane();
        InstitutionTable = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InstitutionList.setBackground(new java.awt.Color(0, 102, 102));

        InstitutionSelectLabel.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        InstitutionSelectLabel.setForeground(new java.awt.Color(240, 240, 240));
        InstitutionSelectLabel.setText("Institution selection");

        InstitutionTable.setBackground(new java.awt.Color(125, 178, 178));
        InstitutionTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InstitutionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Institution PK", "Institution Name"
            }
        ));
        TableInstitution.setViewportView(InstitutionTable);

        BackButton.setFont(new java.awt.Font("Felix Titling", 0, 13)); // NOI18N
        BackButton.setText("Back");
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout InstitutionListLayout = new javax.swing.GroupLayout(InstitutionList);
        InstitutionList.setLayout(InstitutionListLayout);
        InstitutionListLayout.setHorizontalGroup(
            InstitutionListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstitutionListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InstitutionListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InstitutionListLayout.createSequentialGroup()
                        .addComponent(TableInstitution, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InstitutionListLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(InstitutionListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InstitutionListLayout.createSequentialGroup()
                                .addComponent(InstitutionSelectLabel)
                                .addGap(265, 265, 265))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InstitutionListLayout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(241, 241, 241))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InstitutionListLayout.createSequentialGroup()
                                .addComponent(BackButton)
                                .addGap(364, 364, 364))))))
        );
        InstitutionListLayout.setVerticalGroup(
            InstitutionListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstitutionListLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(InstitutionSelectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(TableInstitution, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BackButton)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InstitutionList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InstitutionList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstitutionList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstitutionList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstitutionList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstitutionList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstitutionList().setVisible(true);
            }
        });
    }
    public void setTableInst (DefaultTableModel x){
        InstitutionTable.setModel(x);
    }
    
    private void ButtonHandler(){
         BackButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
    }
    
    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt){
        new GUIMainMenu().setVisible(true);
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel InstitutionList;
    private javax.swing.JLabel InstitutionSelectLabel;
    private javax.swing.JTable InstitutionTable;
    private javax.swing.JScrollPane TableInstitution;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
    
    public JButton getBackButton() {
        return BackButton;
    }
    
    public void ActionListener (ActionListener x){
        BackButton.addActionListener(x);
    }
    
    public void addMouseAdapter(MouseAdapter x){
        InstitutionTable.addMouseListener(x);
    }
    
    public ArrayList<InNeedInstitution> InstitutionList (){
        ArrayList<InNeedInstitution> InstList = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");  
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/do-nation","root",""); 
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM InNeedInstitution");
            InNeedInstitution inst;
            while (rs.next()){
                inst = new InNeedInstitution(rs.getInt("InNeedPK"), rs.getString("InstName"));
                InstList.add(inst);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Failed to Connect to Database","Error Connection", 0); 
        }
        return InstList;
    }
    
    public void showInstList(){
        ArrayList<InNeedInstitution> list = InstitutionList();
        DefaultTableModel model = (DefaultTableModel)InstitutionTable.getModel();
        Object[] row = new Object[2];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getInNeedPK();
            row[1] = list.get(i).getInstName();
            model.addRow(row);
        }
    }
}
